### ISSUE TITLE
Bug: Undefined CSS custom property for "--modal-button-ease"

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/react-modal#3]
Specifically on the `.modal--exiting` styles, there are two values which do not exist unless used within the corgi setup. Let's make those values generic:
- `var(--ease-back-in)`
- `var(--ease-in)`

**Comment by Udassi-Pawan** [comment]
I would like to work on this issue, would you assign it to me?

**Comment by andrewrubin** [comment]
Hey @Udassi-Pawan, sure thing. Thanks in advance 😃

**Comment by andrewrubin** [comment]
Fixed by #4
