### ISSUE TITLE
triggerRef should also accept a DOM node / HTMLElement

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/react-modal#6]
# The problem
Passing a React ref to the Modal component's `triggerRef` works great for shifting focus to the trigger element on close. However, when you're maintaining a _list_ of refs (via some kind of loop for example) your ref becomes an array of DOM nodes, rather than an array of React refs.

## The current (hacky) solution
First, set up our list of triggers in a React ref:
```jsx
const buttonData = [
  "Item 1",
  "Item 2",
  "Item 3",
]

function ListOfModalTriggerButtons () {
  const allTheTriggers = useRef([])

  return (
    <>
      buttonData.map((item, i) => (
        <button
          key={item}
          // add the DOM nodes to the list, which itself is a ref
          ref={(domNode) => allTheTriggers.current[i] = domNode}
        />
      ))
    </>
  )
```

Then fool React into thinking it is receiving a ref on the `triggerRef` prop
```jsx
function SomeAbstractedModal () {
  const { modalState, toggleModal } = useModal()

  // assume this subscribes to a context or something — this implementation is unimportant.
  // basically grab the appropriate DOM element from your list, however you maybe be doing that:
  const triggerButtonDOMNode = getTriggerFromList()
  
  // the smelly part, pt.1:
  const hackyRefObject = useMemo(
    () => ({ current: triggerButtonDOMNode }),
    [triggerButtonDOMNode]
  );

  <Modal
    toggleFunction={toggleModal}
    // the smelly part, pt.2:
    triggerRef={hackyRefObject}
  />
    
}
```

## Proposed solution
I think the solution of wrapping a DOM node in an Object with a `current` property is fine, albeit hacky, but I really don't want the developer to have to think about that. I'm suggesting we handle the wrapping of the DOM node in the library itself. So `triggerRef` will first check to see if it's actually a ref, otherwise it'll wrap it like above.

Please provide your thoughts, there may very well be a better way to implement this.

**Comment by marlonmarcello** [comment]
I think this is a very specific and niche use case, the package should not be the one to take care of that. Specially because this is a non-react way of doing things.  
Any time you are dealing directly with DOM Nodes it's a good idea to stop and see if you can avoid that. I know that for libraries like GSAP you can't, but maybe some kind of composition can fix this.

**Comment by andrewrubin** [comment]
Fair point, let's close this one
